velvet.components += m68k z80 sn76489

velvet.objects += velvet-md-interface
velvet.objects += velvet-md-cpu velvet-md-apu velvet-md-vdp velvet-md-psg velvet-md-ym2612
velvet.objects += velvet-md-mcd
velvet.objects += velvet-md-system velvet-md-cartridge velvet-md-expansion
velvet.objects += velvet-md-controller

$(object.path)/velvet-md-interface.o:  $(velvet.path)/md/interface/interface.cpp
$(object.path)/velvet-md-cpu.o:        $(velvet.path)/md/cpu/cpu.cpp
$(object.path)/velvet-md-apu.o:        $(velvet.path)/md/apu/apu.cpp
$(object.path)/velvet-md-vdp.o:        $(velvet.path)/md/vdp/vdp.cpp
$(object.path)/velvet-md-psg.o:        $(velvet.path)/md/psg/psg.cpp
$(object.path)/velvet-md-ym2612.o:     $(velvet.path)/md/ym2612/ym2612.cpp
$(object.path)/velvet-md-mcd.o:        $(velvet.path)/md/mcd/mcd.cpp
$(object.path)/velvet-md-system.o:     $(velvet.path)/md/system/system.cpp
$(object.path)/velvet-md-cartridge.o:  $(velvet.path)/md/cartridge/cartridge.cpp
$(object.path)/velvet-md-expansion.o:  $(velvet.path)/md/expansion/expansion.cpp
$(object.path)/velvet-md-controller.o: $(velvet.path)/md/controller/controller.cpp
