velvet.components += tlcs900h z80 t6w28

velvet.objects += velvet-ngp-interface velvet-ngp-system velvet-ngp-cartridge
velvet.objects += velvet-ngp-cpu velvet-ngp-apu velvet-ngp-vpu velvet-ngp-psg

$(object.path)/velvet-ngp-interface.o: $(velvet.path)/ngp/interface/interface.cpp
$(object.path)/velvet-ngp-system.o:    $(velvet.path)/ngp/system/system.cpp
$(object.path)/velvet-ngp-cartridge.o: $(velvet.path)/ngp/cartridge/cartridge.cpp
$(object.path)/velvet-ngp-cpu.o:       $(velvet.path)/ngp/cpu/cpu.cpp
$(object.path)/velvet-ngp-apu.o:       $(velvet.path)/ngp/apu/apu.cpp
$(object.path)/velvet-ngp-vpu.o:       $(velvet.path)/ngp/vpu/vpu.cpp
$(object.path)/velvet-ngp-psg.o:       $(velvet.path)/ngp/psg/psg.cpp
