velvet.components += sm83 m93lcx6

velvet.objects += velvet-gb-interface velvet-gb-system
velvet.objects += velvet-gb-bus velvet-gb-cartridge
velvet.objects += velvet-gb-cpu velvet-gb-ppu velvet-gb-apu

$(object.path)/velvet-gb-interface.o: $(velvet.path)/gb/interface/interface.cpp
$(object.path)/velvet-gb-system.o:    $(velvet.path)/gb/system/system.cpp
$(object.path)/velvet-gb-cartridge.o: $(velvet.path)/gb/cartridge/cartridge.cpp
$(object.path)/velvet-gb-bus.o:       $(velvet.path)/gb/bus/bus.cpp
$(object.path)/velvet-gb-cpu.o:       $(velvet.path)/gb/cpu/cpu.cpp
$(object.path)/velvet-gb-ppu.o:       $(velvet.path)/gb/ppu/ppu.cpp
$(object.path)/velvet-gb-apu.o:       $(velvet.path)/gb/apu/apu.cpp
