velvet.objects += velvet-n64-interface velvet-n64-memory velvet-n64-system
velvet.objects += velvet-n64-cartridge velvet-n64-controller velvet-n64-dd
velvet.objects += velvet-n64-mi velvet-n64-vi velvet-n64-ai
velvet.objects += velvet-n64-pi velvet-n64-ri velvet-n64-si
velvet.objects += velvet-n64-rdram velvet-n64-cpu velvet-n64-rdp velvet-n64-rsp

$(object.path)/velvet-n64-interface.o:  $(velvet.path)/n64/interface/interface.cpp
$(object.path)/velvet-n64-memory.o:     $(velvet.path)/n64/memory/memory.cpp
$(object.path)/velvet-n64-system.o:     $(velvet.path)/n64/system/system.cpp
$(object.path)/velvet-n64-cartridge.o:  $(velvet.path)/n64/cartridge/cartridge.cpp
$(object.path)/velvet-n64-controller.o: $(velvet.path)/n64/controller/controller.cpp
$(object.path)/velvet-n64-dd.o:         $(velvet.path)/n64/dd/dd.cpp
$(object.path)/velvet-n64-sp.o:         $(velvet.path)/n64/sp/sp.cpp
$(object.path)/velvet-n64-dp.o:         $(velvet.path)/n64/dp/dp.cpp
$(object.path)/velvet-n64-mi.o:         $(velvet.path)/n64/mi/mi.cpp
$(object.path)/velvet-n64-vi.o:         $(velvet.path)/n64/vi/vi.cpp
$(object.path)/velvet-n64-ai.o:         $(velvet.path)/n64/ai/ai.cpp
$(object.path)/velvet-n64-pi.o:         $(velvet.path)/n64/pi/pi.cpp
$(object.path)/velvet-n64-ri.o:         $(velvet.path)/n64/ri/ri.cpp
$(object.path)/velvet-n64-si.o:         $(velvet.path)/n64/si/si.cpp
$(object.path)/velvet-n64-rdram.o:      $(velvet.path)/n64/rdram/rdram.cpp
$(object.path)/velvet-n64-cpu.o:        $(velvet.path)/n64/cpu/cpu.cpp
$(object.path)/velvet-n64-rdp.o:        $(velvet.path)/n64/rdp/rdp.cpp
$(object.path)/velvet-n64-rsp.o:        $(velvet.path)/n64/rsp/rsp.cpp

flags += -msse4.2
options += -msse4.2
