velvet.components += v30mz m93lcx6

velvet.objects += velvet-ws-interface velvet-ws-system
velvet.objects += velvet-ws-memory velvet-ws-eeprom velvet-ws-cartridge
velvet.objects += velvet-ws-cpu velvet-ws-ppu velvet-ws-apu

$(object.path)/velvet-ws-interface.o: $(velvet.path)/ws/interface/interface.cpp
$(object.path)/velvet-ws-system.o:    $(velvet.path)/ws/system/system.cpp
$(object.path)/velvet-ws-memory.o:    $(velvet.path)/ws/memory/memory.cpp
$(object.path)/velvet-ws-eeprom.o:    $(velvet.path)/ws/eeprom/eeprom.cpp
$(object.path)/velvet-ws-cartridge.o: $(velvet.path)/ws/cartridge/cartridge.cpp
$(object.path)/velvet-ws-cpu.o:       $(velvet.path)/ws/cpu/cpu.cpp
$(object.path)/velvet-ws-ppu.o:       $(velvet.path)/ws/ppu/ppu.cpp
$(object.path)/velvet-ws-apu.o:       $(velvet.path)/ws/apu/apu.cpp
