velvet.components += z80 sn76489 ym2413

velvet.objects += velvet-ms-interface
velvet.objects += velvet-ms-cpu velvet-ms-vdp velvet-ms-psg velvet-ms-opll
velvet.objects += velvet-ms-system velvet-ms-cartridge
velvet.objects += velvet-ms-controller

$(object.path)/velvet-ms-interface.o:  $(velvet.path)/ms/interface/interface.cpp
$(object.path)/velvet-ms-cpu.o:        $(velvet.path)/ms/cpu/cpu.cpp
$(object.path)/velvet-ms-vdp.o:        $(velvet.path)/ms/vdp/vdp.cpp
$(object.path)/velvet-ms-psg.o:        $(velvet.path)/ms/psg/psg.cpp
$(object.path)/velvet-ms-opll.o:       $(velvet.path)/ms/opll/opll.cpp
$(object.path)/velvet-ms-system.o:     $(velvet.path)/ms/system/system.cpp
$(object.path)/velvet-ms-cartridge.o:  $(velvet.path)/ms/cartridge/cartridge.cpp
$(object.path)/velvet-ms-controller.o: $(velvet.path)/ms/controller/controller.cpp
