velvet.components += huc6280 msm5205

velvet.objects += velvet-pce-interface
velvet.objects += velvet-pce-cpu velvet-pce-vdp velvet-pce-psg velvet-pce-pcd
velvet.objects += velvet-pce-system velvet-pce-cartridge
velvet.objects += velvet-pce-controller

$(object.path)/velvet-pce-interface.o:  $(velvet.path)/pce/interface/interface.cpp
$(object.path)/velvet-pce-cpu.o:        $(velvet.path)/pce/cpu/cpu.cpp
$(object.path)/velvet-pce-vdp.o:        $(velvet.path)/pce/vdp/vdp.cpp
$(object.path)/velvet-pce-psg.o:        $(velvet.path)/pce/psg/psg.cpp
$(object.path)/velvet-pce-pcd.o:        $(velvet.path)/pce/pcd/pcd.cpp
$(object.path)/velvet-pce-system.o:     $(velvet.path)/pce/system/system.cpp
$(object.path)/velvet-pce-cartridge.o:  $(velvet.path)/pce/cartridge/cartridge.cpp
$(object.path)/velvet-pce-controller.o: $(velvet.path)/pce/controller/controller.cpp
