velvet.components += z80 tms9918 v9938 ay38910 ym2413

velvet.objects += velvet-msx-interface velvet-msx-system velvet-msx-keyboard
velvet.objects += velvet-msx-cartridge velvet-msx-controller
velvet.objects += velvet-msx-cpu velvet-msx-vdp velvet-msx-psg

$(object.path)/velvet-msx-interface.o:  $(velvet.path)/msx/interface/interface.cpp
$(object.path)/velvet-msx-system.o:     $(velvet.path)/msx/system/system.cpp
$(object.path)/velvet-msx-keyboard.o:   $(velvet.path)/msx/keyboard/keyboard.cpp
$(object.path)/velvet-msx-cartridge.o:  $(velvet.path)/msx/cartridge/cartridge.cpp
$(object.path)/velvet-msx-controller.o: $(velvet.path)/msx/controller/controller.cpp
$(object.path)/velvet-msx-cpu.o:        $(velvet.path)/msx/cpu/cpu.cpp
$(object.path)/velvet-msx-vdp.o:        $(velvet.path)/msx/vdp/vdp.cpp
$(object.path)/velvet-msx-psg.o:        $(velvet.path)/msx/psg/psg.cpp
