velvet.objects += velvet-ps1-interface
velvet.objects += velvet-ps1-memory
velvet.objects += velvet-ps1-system
velvet.objects += velvet-ps1-disc
velvet.objects += velvet-ps1-controller
velvet.objects += velvet-ps1-cpu
velvet.objects += velvet-ps1-gpu
velvet.objects += velvet-ps1-spu
velvet.objects += velvet-ps1-interrupt
velvet.objects += velvet-ps1-peripheral
velvet.objects += velvet-ps1-dma
velvet.objects += velvet-ps1-timer

$(object.path)/velvet-ps1-interface.o:  $(velvet.path)/ps1/interface/interface.cpp
$(object.path)/velvet-ps1-memory.o:     $(velvet.path)/ps1/memory/memory.cpp
$(object.path)/velvet-ps1-system.o:     $(velvet.path)/ps1/system/system.cpp
$(object.path)/velvet-ps1-controller.o: $(velvet.path)/ps1/controller/controller.cpp
$(object.path)/velvet-ps1-disc.o:       $(velvet.path)/ps1/disc/disc.cpp
$(object.path)/velvet-ps1-cpu.o:        $(velvet.path)/ps1/cpu/cpu.cpp
$(object.path)/velvet-ps1-gpu.o:        $(velvet.path)/ps1/gpu/gpu.cpp
$(object.path)/velvet-ps1-spu.o:        $(velvet.path)/ps1/spu/spu.cpp
$(object.path)/velvet-ps1-interrupt.o:  $(velvet.path)/ps1/interrupt/interrupt.cpp
$(object.path)/velvet-ps1-peripheral.o: $(velvet.path)/ps1/peripheral/peripheral.cpp
$(object.path)/velvet-ps1-dma.o:        $(velvet.path)/ps1/dma/dma.cpp
$(object.path)/velvet-ps1-timer.o:      $(velvet.path)/ps1/timer/timer.cpp
